//
//  welcomeWorker.swift
//  Meteo App
//
//  Created by Yakoubi Mohammed on 24/9/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class welcomeWorker
{
  func doSomeWork()
  {
  }
}
